
project_id = "djczgpmhrbirbqrycodq"

[functions.proactive-investigation]
verify_jwt = false

[auth.email]
enable_confirmations = false

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[functions.get-mapbox-token]
verify_jwt = false
