// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djczgpmhrbirbqrycodq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqY3pncG1ocmJpcmJxcnljb2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDc0MDMsImV4cCI6MjA2MjcyMzQwM30.hFrbeO7mmXXYdAkzoVT88O8enMOMqd8C94EfermuCas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);